version: '3.7'

services:

    webserver:
        
        build:
            context: ./rastack/coding-hour
            dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true